import Head from "next/head";
import Waste from "@/../public/Assets/waste.svg";
import Collab from "@/../public/Assets/collab.svg";
import Logistics from "@/../public/Assets/logistics.svg";
import Link from "next/link";
import Image from "next/image";
import Iron from "@/../public/Assets/ticker/iron.svg";
import Steel from "@/../public/Assets/ticker/steel.svg";
import Marquee from "react-fast-marquee";
import Info from "@/../public/Assets/info.svg";
import Arrow from "@/../public/Assets/arrow.svg";
import FeatureModal from "@/component/FeatureModal";
import TopBlob from "@/../public/Assets/BlobTop.svg";
import BottomBlob from "@/../public/Assets/BlobBottom.svg";
import Navbar from "@/component/Navbar";
import { useEffect, useState } from "react";
import { db } from "@/../firebase";
import { collection, getDocs } from "firebase/firestore";
export default function Home() {
  const [forSale, setForSale] = useState([]);
  const fetchForSale = async () => {
    try {
      const trashSnap = await getDocs(collection(db, "trash"));
      setForSale(trashSnap.docs.map((doc) => doc.data()));
      // trashSnap.forEach((doc) => {
      //   setForSale([...forSale, doc.data()]);
      //   console.log(doc.data());
      // });
    } catch (err) {
      console.log(err);
    }
  };
  useEffect(() => {
    fetchForSale();
  }, []);
  const features = [
    {
      title: "Waste",
      path: "/trash",
      image: Waste,
    },
    {
      title: "Collab",
      path: "/collab",
      image: Collab,
    },
    {
      title: "Logistics",
      path: "/logistics",
      image: Logistics,
    },
  ];
  const tickerData = [];
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col justify-between min-h-screen ">
        <Navbar />
        {/* <main> */}
        <div className="py-16 text-black text-center">
          <h1 className="font-bold text-6xl">EcoGo</h1>
          <p className="mt-4">Sustainable consumption & production</p>
        </div>
        <div className="flex w-full gap-x-4 items-center justify-center">
          <div className="w-full flex justify-center gap-x-8">
            {features.map((feature, idx) => {
              return (
                <div
                  key={idx}
                  className="scale-90  transition-all duration-300 ease-in-out"
                >
                  <div className="flex flex-col items-center justify-center relative">
                    <button className="absolute left-[7%] bottom-[25%]">
                      {/* <Image src={Info} alt="Info" /> */}
                      <FeatureModal
                        name={feature.title}
                        child={<div>Hi</div>}
                      />
                    </button>
                    <Image src={feature.image} alt={feature.title} />
                    <Link
                      href={feature.path}
                      className="absolute bottom-[10%] right-[10%] hover:scale-125 transition-all duration-300"
                    >
                      <Image src={Arrow} alt="Arrow" />
                    </Link>
                  </div>
                </div>
              );
            })}
          </div>
        </div>
        <div className="flex w-full">
          <h1 className="text-white font-bold p-2 mx-auto bg-black">
            Products for sale:
          </h1>
          <Marquee
            pauseOnHover
            speed={85}
            className="bg-gradient-to-r  from-black via-gray-600  to-black "
          >
            {forSale.length > 0 &&
              forSale.map((trash, idx) => {
                return (
                  <Link
                    href={`/trash/${trash.trashId}`}
                    key={idx}
                    className="flex gap-x-3 mx-4 p-2 rounded-md bg-gray-200 "
                  >
                    {trash.name}
                  </Link>
                );
              })}
            {forSale.length > 0 &&
              forSale.map((trash, idx) => {
                return (
                  <Link
                    href={`/trash/${trash.trashId}`}
                    key={idx}
                    className="flex gap-x-3 mx-4 p-2 rounded-md bg-gray-200 "
                  >
                    {trash.name}
                  </Link>
                );
              })}
            {forSale.length > 0 &&
              forSale.map((trash, idx) => {
                return (
                  <Link
                    href={`/trash/${trash.trashId}`}
                    key={idx}
                    className="flex gap-x-3 mx-4 p-2 rounded-md bg-gray-200 "
                  >
                    {trash.name}
                  </Link>
                );
              })}
          </Marquee>
        </div>
        {/* </main> */}
      </div>
    </>
  );
}
