import Head from "next/head";
import Waste from "@/../public/Assets/waste.svg";
import Collab from "@/../public/Assets/collab.svg";
import Logistics from "@/../public/Assets/logistics.svg";
import Link from "next/link";
import Image from "next/image";
import Iron from "@/../public/Assets/ticker/iron.svg";
import Steel from "@/../public/Assets/ticker/steel.svg";
import Marquee from "react-fast-marquee";
import Info from "@/../public/Assets/info.svg";
import Arrow from "@/../public/Assets/arrow.svg";
import FeatureModal from "@/component/FeatureModal";

export default function Home() {
  const features = [
    {
      title: "Waste",
      path: "/trash",
      image: Waste,
    },
    {
      title: "Collab",
      path: "/collab",
      image: Collab,
    },
    {
      title: "Logistics",
      path: "/logistics",
      image: Logistics,
    },
  ];
  const tickerData = [];
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col min-h-screen ">
        {/* <main> */}
        <div className="py-20 text-black text-center">
          <h1 className="font-bold text-6xl">LOREM IPSUM DOLOR</h1>
          <p className="mt-4">sit amet, consectetur adipiscing elit</p>
        </div>
        <div className="flex w-full gap-x-4 items-center justify-center">
          <div className="w-full flex justify-center gap-x-8">
            {features.map((feature, idx) => {
              return (
                <div
                  key={idx}
                  className=" hover:scale-110 transition-all duration-300 ease-in-out"
                >
                  <div className="flex flex-col items-center justify-center relative">
                    <button className="absolute left-[5%] bottom-[25%]">
                      {/* <Image src={Info} alt="Info" /> */}
                      <FeatureModal
                        name={feature.title}
                        child={<div>Hi</div>}
                      />
                    </button>
                    <Image src={feature.image} alt={feature.title} />
                    <Link
                      href={feature.path}
                      className="absolute bottom-[10%] right-[10%]"
                    >
                      <Image src={Arrow} alt="Arrow" />
                    </Link>
                  </div>
                </div>
              );
            })}
          </div>
        </div>
        {/* <div className="grow"> */}
        <Marquee
          pauseOnHover
          className="py-4 bg-gradient-to-r from-black via-gray-600 mt-6 to-black"
        >
          {[...Array(10)].map((_, idx) => {
            return (
              <div key={idx} className="flex gap-x-3 mx-3">
                <Image src={Iron} alt="Iron" />
                <Image src={Steel} alt="Steel" />
              </div>
            );
          })}
        </Marquee>
        {/* </div> */}
        {/* </main> */}
      </div>
    </>
  );
}
